config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'geofences#index'
  resources :geofences
  resources :time_trackings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/geofence.rb
class Geofence < ApplicationRecord

end

app/models/time_tracking.rb
class TimeTracking < ApplicationRecord
  before_create :set_time
  validates :latitude, presence: true
  validates :longitude, presence: true

  def set_time
    self.time = Time.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/geofences_controller.rb
class GeofencesController < ApplicationController

  def index
    @geofences =  Geofence.all
  end

def new
  @geofence = Geofence.new
end

def create
  @geofence = Geofence.create(geofence_params)
  redirect_to geofences_path
end

def show
  @geofence = Geofence.find(params[:id])
end

private

  def geofence_params
    params.require(:geofence).permit(:latitude, :longitude, :radius)
  end

end

app/controllers/time_trackings_controller.rb
class TimeTrackingsController < ApplicationController

  def index
    @time_trackings = TimeTracking.all

    if params[:start] && params[:end]
      @time_trackings = TimeTracking.where('time >= ? AND time <= ?', get_time(params[:start]), get_time(params[:end]))
    end
  end

  def new
    @timetracking = TimeTracking.new
    @geofences = Geofence.all.map { |geofence| [geofence.latitude, geofence.longitude, geofence.radius] }
  end

  def create
    @timetracking = TimeTracking.create(timetracking_params)
    redirect_to time_trackings_path
  end

  def show

  end


  def timetracking_params
    params.require(:time_tracking).permit(:comment, :latitude, :longitude)
  end

  private

  def get_time(date)
    # solução baseada na seguinte resposta de https://stackoverflow.com/a/30543697
    Time.strptime(date, "%m/%d/%Y %I:%M %p")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/geofences/index.html.erb
<h1>Geofences</h1>
<table>
<% @geofences.each do |geofence| %>
  <tr>
    <td><%= geofence.latitude %></td>
    <td><%= geofence.longitude %></td>
    <td><%= geofence.radius %></td>
    <td>
      <%= link_to 'Show Geofence', action: 'show', id: geofence %>
    </td>
  </tr>
<% end %>

</table>

  <p><%= link_to "New Geofence", new_geofence_path %></p>

app/views/geofences/new.html.erb
<%= form_for @geofence, url: geofences_path, html: {class: "nifty_form"} do |f| %>
  <%= f.label :latitude, 'Latitude:' %>
  <p><%= f.text_field :latitude %></p>
  <%= f.label :longitude, 'Longitude:' %>
  <p><%= f.text_field :longitude %></p>
  <%= f.label :radius, 'Raio:' %>
  <p><%= f.text_field :radius %></p>
  <%= f.submit "Create" %>
<% end %>

app/views/geofences/show.html.erb
<h1>Geofence</h1>

Latitude: <%= @geofence.latitude %>
<p>Longitude: <%= @geofence.longitude %></p>
<p>Radius: <%= @geofence.radius %></p>

<p><%= link_to "Voltar", geofences_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCGPAaW1pdj1eQDgVRaPxTOfs8S8wZE3J8&libraries=geometry">
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/time_trackings/index.html.erb
<h1>TimeTrackings</h1>
<div class="container">
  <%= form_tag time_trackings_path, method: :get  do |f| %>

    <div class="row">
      <div class="col-md-10">
        <%= label_tag 'Time' %>
        <%= text_field_tag 'start', params[:start], class: 'datetimepicker'%>
        <%= text_field_tag 'end', params[:end], class: 'datetimepicker'%>

      </div>
    </div>

    <%= submit_tag 'Filtrar' %>
  <% end %>

</div>

<% @time_trackings.each do |time_tracking| %>
  <p>
    <%= time_tracking.comment %>
    <%= time_tracking.latitude %>
  </p>
<% end %>

<script>
    $(function () {
        $('.datetimepicker').datetimepicker();
    });
</script>

app/views/time_trackings/new.html.erb
<%= form_for @timetracking, url: time_trackings_path, html: {class: "nifty_form"} do |f| %>
  <%= f.label :comment, 'Comentários:' %>
  <p><%= f.text_area :comment %></p>
  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>
  <%= f.submit "Create", disabled: true, id: 'submit' %>
<% end %>
<div id="clock"> </div>

<style>
  #clock {
    font-family: "Helvetica Neue", Helvetica, Arial, Sans-Serif;
    color: #FA8072;
    font-size: 56px;
    text-align: center;
    padding-top: 40px;
    padding-bottom: 40px;

  }
</style>
<script>
    function currentTime() {
        var date = new Date(); /* creating object of Date class */
        var hour = date.getHours();
        var min = date.getMinutes();
        var sec = date.getSeconds();
        hour = updateTime(hour);
        min = updateTime(min);
        sec = updateTime(sec);
        document.getElementById("clock").innerText = hour + " : " + min + " : " + sec; /* adding time to the div */
        var t = setTimeout(function(){ currentTime() }, 1000); /* setting timer */
    }

    function updateTime(k) {
        if (k < 10) {
            return "0" + k;
        }
        else {
            return k;
        }
    }

    currentTime(); /* calling currentTime() function to initiate the process */

    $( document ).ready(getLocation());
    var x=document.getElementById("demo");
    function getLocation()
    {
        if (navigator.geolocation)
        {

            navigator.geolocation.getCurrentPosition(setPosition,showError);
        }
        else{x.innerHTML="Seu browser não suporta Geolocalização.";}
    }
    // baseado em https://stackoverflow.com/a/20044849
    function setPosition(position)
    {
        document.getElementById("time_tracking_latitude").value = position.coords.latitude;
        document.getElementById("time_tracking_longitude").value = position.coords.longitude;

        const geofences = JSON.parse('<%= @geofences.to_json.html_safe %>');
        let inside = false;
        geofences.forEach((geofence) => {
            if (google.maps.geometry.spherical.computeDistanceBetween(
                new google.maps.LatLng( position.coords.latitude,position.coords.longitude ),
                new google.maps.LatLng( geofence[0],geofence[1] )
            ) <= geofence[2]) {
                inside = true;
            }
        });

        if(inside) {
            $('#submit').removeAttr('disabled');
        } else {
            console.log('Você está fora da área permitida.')
        }
    }
    function showError(error)
    {
        switch(error.code)
        {
            case error.PERMISSION_DENIED:
                x.innerHTML="Usuário rejeitou a solicitação de Geolocalização."
                break;
            case error.POSITION_UNAVAILABLE:
                x.innerHTML="Localização indisponível."
                break;
            case error.TIMEOUT:
                x.innerHTML="A requisição expirou."
                break;
            case error.UNKNOWN_ERROR:
                x.innerHTML="Algum erro desconhecido aconteceu."
                break;
        }
    }
</script>